# Generated by Django 2.1.3 on 2019-04-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_passes', models.IntegerField()),
                ('model_id', models.IntegerField()),
                ('loss_function', models.CharField(max_length=30)),
                ('sequence_length', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('recur_button', models.BooleanField()),
                ('drop_out', models.FloatField()),
                ('max_grad', models.IntegerField()),
                ('variational_recurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField()),
                ('num_nets', models.IntegerField()),
                ('model_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('model_duration', models.IntegerField()),
                ('model_created', models.DateTimeField(auto_now_add=True)),
                ('model_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
